import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Indication Plus Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='grid h-screen place-items-center'>
        <h1 className="text-5xl font-bold">
          Welcome Welcome !<span className='flex text-red-600'>I’m form cambodia</span>
        </h1>
        <h1 className="grid h-screen text-9xl place-items-center font-bold underline">
          Hello world!
        </h1>
      </main>

      
    </>
    
  )
}
